backend:
  name: github
  repo: BJJohnston/blindfold
media_folder: static/assets
public_folder: /assets
collections:
  - name: home
    label: home
    folder: src/pages/markdown/home
    create: true
    fields:
       - { name: templateKey, label: Template Key, widget: string }
       - { name: title, label: Title, widget: string }
       - { name: description, label: Description, widget: string }